# Generated by Django 6.0.2 on 2026-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to='cars/'),
            preserve_default=False,
        ),
    ]
